export const playlistData = [
	{
		id: 1,
		trackName: 'Guilt',
		trackAuthor: 'Nero',
		trackAlbum: 'Welcome Reality',
		trackDuration: '4:44',
	},
	{
		id: 2,
		trackName: 'Elektro',
		trackAuthor: 'Dynoro, Outwork, Mr. Gee',
		trackAlbum: 'Elektro',
		trackDuration: '2:22',
	},
	{
		id: 3,
		trackName: 'I’m Fire',
		trackAuthor: 'Ali Bakgor',
		trackAlbum: 'I’m Fire',
		trackDuration: '2:22',
	},
	{
		id: 4,
		trackName: 'Non Stop',
		trackNameSpan: '(Remix)',
		trackAuthor: 'Стоункат, Psychopath',
		trackAlbum: 'Non Stop',
		trackDuration: '4:12',
	},
	{
		id: 5,
		trackName: 'Run Run',
		trackNameSpan: '(feat. AR/CO)',
		trackAuthor: 'Jaded, Will Clarke, AR/CO',
		trackAlbum: 'Run Run',
		trackDuration: '2:54',
	},
	{
		id: 6,
		trackName: 'Eyes on Fire',
		trackNameSpan: '(Zeds Dead Remix)',
		trackAuthor: 'Blue Foundation, Zeds Dead',
		trackAlbum: 'Eyes on Fire',
		trackDuration: '5:20',
	},
	{
		id: 7,
		trackName: 'Mucho Bien',
		trackNameSpan: '(Hi Profile Remix)',
		trackAuthor: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
		trackAlbum: 'Mucho Bien',
		trackDuration: '3:41',
	},
	{
		id: 8,
		trackName: 'Knives n Cherries',
		trackAuthor: 'minthaze',
		trackAlbum: 'Captivating',
		trackDuration: '1:48',
	},
	{
		id: 9,
		trackName: 'Knives n Cherries',
		trackAuthor: 'minthaze',
		trackAlbum: 'Captivating',
		trackDuration: '1:48',
	},
];